apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: nginx
    image: nginx

resources:
  request:
    memory: "78mi"
    cpu: "100m"
  limits:
    memory: "100mi"
    cpu: "120m"